### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by dunglas**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/XlK1Rd).

### CODE REVIEW

**Comment by vincentchalamon** [comment]
Can you add the badge in the README.md?

**Comment by vincentchalamon** [comment]
You removed author name from header, I can understand. But can you add author on class PHPDoc like:

``` php
/**
 * @author Vincent Chalamon <vincentchalamon@gmail.com>
 */
class Foo
```

**Comment by dunglas** [comment]
I just applied our global StyleCI config but credit must be given back to you.

**Comment by vincentchalamon** [comment]
Ping @dunglas: this PR blocks the other PRs

**Comment by dunglas** [comment]
I don't have access to a computer 😵. This is a just the patch from StyleCI. Feel free to close and to fix CS in another PRz

**Pull request closed without merging**
