### PR TITLE
[WIP] add adapters for api-platform v1

### PR DESCRIPTION
**Pull request by Simperfit**
- [ ] Add adapter for V1
  Which means to 
  - [ ] Create the good interface and objects
  - [ ] Refactor the current behavior and add the adapter to services
  - [ ] Test it

the v2 will be in another commit :
- [ ] Add adapter for V2
  Which means to 
  - [x] Supports PHP7
  - [ ] Use the annontations
  - [ ] Test it

@vincentchalamon : could you add the other things todo please if I miss some of them ?

### CODE REVIEW

**Comment by vincentchalamon** [comment]
I think you should split ApiPlatform1 & ApiPlatform2 adapters in several PRs, cause it will be a lot of work:
1. Implements Adapter workflow (entities, `AdapterInterface`, etc…)
2. Implements ApiPlatform1Adapter & related code
3. Implements ApiPlatform2Adapter & related code

Here is, IMO, the work to do:
- Create `AdapterInterface`
- Create PostmanGeneratorBundle entities: ResourceCollection, Resource, Operation, ClassMetadata
- Create ApiPlatform1Adapter:
  - Adapter should build & return PostmanGeneratorBundle entities from related service: collection, resource, operation…
  - Adapt PostmanGeneratorBundle code: replace ApiPlatform1 dependencies with AdapterInterface object, which allows to retrieve collection, resource…

**Comment by vincentchalamon** [comment]
Supports of PHP7 is already done through Travis: https://github.com/api-platform/postman-collection-generator/blob/master/.travis.yml#L14

**Comment by vincentchalamon** [comment]
One of the most difficult part should also be to test both ApiPlatform versions in functional tests

**Comment by dunglas** [comment]
To test both version, you should modify dynamically the `composer.json` file in `.travis.yml`.

**Comment by vincentchalamon** [comment]
This PR is out of date as API Platform 2 supports [Swagger](http://swagger.io/)

**Pull request closed without merging**
